;>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
; 1DT301, Computer Technology I
; Date: 2015-09-03
; Author:
; Matus Maruna
; John Charo 
;
; Lab number: 3
; Title: Turning signals 
;
; Hardware: STK600, CPU ATmega2560
;
; Function: The function of this program is to preform ring counter either left or right mimicing the turning signals
;           of a car
;
; Input ports: Port D for switches to trigger an interrupt
;
; Output ports: Port B for LEDs
;
; Subroutines: main loop will output the default car light setup to the LEDs. When sw1 is pressed the "right" subroutine will output the ring counter representing
;              a turn right. When sw3 is pressed the "left" subroutine will output the ring counter representing a turn left. They will then be returned to the main loop

; Included files: m2560def.inc
;
; Other information:
;
; Changes in program: (Description and date)
;<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
.include "m2560def.inc"
.org 0x00
rjmp start

.org INT3addr
rjmp left

.org INT1addr
rjmp right 


.org 0x72
start:
ldi r16, 0x00
out DDRD, r16
ldi r16, 0xFF ; setting portB as output 
out DDRB, r16
ldi r16, 0xFF
out PORTB, r16
; initilizing the stack, copy pasted from the assignment question
ldi r24, HIGH(RAMEND) ; R20 = high part of RAMEND address
out SPH,R24 ; SPH = high part of RAMEND address
ldi R24, low(RAMEND) ; R20 = low part of RAMEND address
out SPL,R24 ; SPL = low part of RAMEND address
ldi r16,0b00000110
out EIMSK, r16
ldi r16,0b10001000
sts EICRA, r16

sei



main: 
ldi r22,0b00111100
out PORTB, r22
call delay 
rjmp main 




delay: 
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; Delay 500 000 cycles
; 500ms at 1.0 MHz
	push r18
    ldi  r18, 3
    ldi  r19, 138
    ldi  r20, 86
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    rjmp PC+1
	pop r18
ret

; subroutine to handle turning left 
left: 
ldi r16, 0b11101100
out portB, r16
call delay
ldi r16, 0b11011100
out portB, r16
call delay
ldi r16, 0b10111100
out portB, r16
call delay
ldi r16, 0b01111100
out portB, r16
call delay
reti
; subroutine to handle turning right 
right: 
ldi r16, 0b00110111
out portB, r16
call delay
ldi r16, 0b00111011
out portB, r16
call delay
ldi r16, 0b00111101
out portB, r16
call delay
ldi r16, 0b00111110
out portB, r16
call delay
reti
